"""
Django settings for simpleboard project.

Generated by 'django-admin startproject' using Django 5.2.8.

Документация:
https://docs.djangoproject.com/en/5.2/topics/settings/
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# -------------------------------------------------------
# Базовая директория проекта
# -------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent


# -------------------------------------------------------
# Безопасность и режим разработки
# -------------------------------------------------------
SECRET_KEY = 'django-insecure-ay^1+n_!l0dsy1eqsd6c4g$eqpe77uo*avg#71e21+rjmiq+@1'  # ключ проекта
DEBUG = True  # Режим отладки (выключать в проде)
ALLOWED_HOSTS = []  # Доступные хосты


# -------------------------------------------------------
# Установленные приложения
# -------------------------------------------------------
INSTALLED_APPS = [
    # Django core
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Приложения проекта
    'board.apps.BoardConfig',  # Основное приложение доски

    # Дополнительные библиотеки
    'django_htmx',  # для HTMX
    'rest_framework',  # DRF
    'rest_framework_simplejwt',  # JWT для API
    'drf_yasg',  # Swagger/OpenAPI документация
]


# -------------------------------------------------------
# DRF (Django REST Framework) настройки
# -------------------------------------------------------
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',  # доступно всем по умолчанию
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # JWT
    ),
}


# -------------------------------------------------------
# Middleware
# -------------------------------------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_htmx.middleware.HtmxMiddleware',  # для HTMX
]


# -------------------------------------------------------
# URL конфигурация проекта
# -------------------------------------------------------
ROOT_URLCONF = 'simpleboard.urls'


# -------------------------------------------------------
# Шаблоны (Templates)
# -------------------------------------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # глобальная папка templates
        'APP_DIRS': True,  # искать шаблоны в приложениях
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',  # доступ к request
                'django.contrib.auth.context_processors.auth',  # доступ к user
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# -------------------------------------------------------
# WSGI
# -------------------------------------------------------
WSGI_APPLICATION = 'simpleboard.wsgi.application'


# -------------------------------------------------------
# База данных (SQLite)
# -------------------------------------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# -------------------------------------------------------
# Проверка паролей
# -------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]


# -------------------------------------------------------
# Локализация
# -------------------------------------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# -------------------------------------------------------
# Статические файлы
# -------------------------------------------------------
STATIC_URL = 'static/'


# -------------------------------------------------------
# Автоматическое поле для PK
# -------------------------------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# -------------------------------------------------------
# Переадресации при логине/логауте
# -------------------------------------------------------
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'
